export const COLLECT_LINK = "APP/COLLECT_LINK";
export const FETCH_LINK = "POST/FETCH_LINK";
export const HANDLE_INPUT = "APP/HANDLE_INPUT";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const HIDE_SHORT_LINK = "APP/HIDE_SHORT_LINK";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const SHOW_SHORT_LINK = "APP/SHOW_SHORT_LINK";
