version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run:
          name: Run tests
          command: yarn test

      - store_artifacts:
          path: test-results

      - store_test_results:
          path: test-results

      - run:
        name: Run linter
        command: yarn lint

workflows:
  version: 2
  Build and Test:
    jobs:
      - build
