export const FETCH_LINK = "POST/FETCH_LINK";
export const FETCH_INPUT = "APP/FETCH_INPUT";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const SHOW_SHORT_LINK = "APP/SHOW_SHORT_LINK";
export const HIDE_SHORT_LINK = "APP/HIDE_SHORT_LINK";
export const ADD_NOTIFICATION = "APP/ADD_NOTIFICATION";
